# This is a basic workflow to help you get started with Actions

name: Python script

# Controls when the workflow will run
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a Python script
        run: python .github/workflows/example.py Hello
      - name: Gather Repository Collaborators
        id: repository-collaborators-response
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.github.com/repos/Bearmijos/Peer-To-Peer-Renting/collaborators
          method: 'GET'
          accept: 200, 404
          headers: '{ Authorization: Bearer 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 }'
          body: ''
          timeout: 10000
          retries: 5

