# This is a basic workflow to help you get started with Actions

name: Python script

# Controls when the workflow will run
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Gather Repository Collaborators
        id: repository-collaborators-response
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.github.com/repos/Bryan-At-Rentmate/Rentmate-Backend/collaborators
          method: 'GET'
          accept: 200, 404
          headers: '{ Authorization: Bearer ${{ secrets.CANDY }} }'
          body: ''
          timeout: 10000
          retries: 5
          log-response: true
      - name: Display
        run: echo " ${{ steps.repository-collaborators-response.outputs.response }}"
      - name: Set Api Response
        id: api-response
        run: echo '::set-output name=MEOW::${{ steps.repository-collaborators-response.outputs.response }}'
      - name: Display
        run: echo " ${{ steps.api-response.outputs.MEOW }}"

      - name: Set Repo Collaborators
        id: random-color-generator
        run: echo '::set-output name=SELECTED_COLOR::green'
      - name: Display Repo Collaborators
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
